### ISSUE TITLE
Dojo Voting Module

### ISSUE THREAD

**Issue by ponderingdemocritus** [dojoengine/origami#48]
This task is to create a voting module based on Dojo Models to allow games to implement voting strategies using Dojo models. For the first version, we should simply demonstrate how to create a voting structure with a basic strategy.

The structure should include:

Primitives (This should be based within a new Governance directory):
- [ ]  Submission of the transaction to execute if the strategy passes quorum. This could be stored in a generic Model structure.
- [ ]  A mechanism to execute the proposed transaction if it passes the strategy.
- [ ]  Definition of the generic strategy and initialization of it. For example, does it require ERC721 votes, ERC20 votes, or a custom Entity within a Dojo world to vote?

Examples:
- [ ]  An example demonstrating the usage of the generic voting primitives based on ERC721 Votes.

Inspiration for this module could be found within the open-zeppelin contracts.

**Comment by ebukizy1** [comment]
will love to work on this assign me

**Comment by ebukizy1** [comment]
good day didnt see anyone assign this task will love to jump on it
