### ISSUE TITLE
[Example]: ERC20 example

### ISSUE THREAD

**Issue by rsodre** [dojoengine/origami#72]
### Feature Request

Create a simple Dojo project deploying a new ERC20 token.

### Proposed Solution

* Dojo project deploying a new ERC20 token.
* React project able to connect a wallet, mint tokens and display balance.

#### TBD:
* What's the best way to structure this example?
  * Dojo project at [dojo/examples](https://github.com/dojoengine/dojo/tree/main/examples)?
  * React dapp at [dojo.js/examples](https://github.com/dojoengine/dojo.js/tree/main/examples)?
  * Both under the same place? Where?

### If the feature is accepted, would you be willing to contribute it?

- [X] Yes I would be willing to contribute

**Comment by EjembiEmmanuel** [comment]
@rsodre I'd love to work on this
