### ISSUE TITLE
[Feature]: ERC-721 Metadata hooks

### ISSUE THREAD

**Issue by rsodre** [dojoengine/origami#79]
### Feature Request

Add a hook to Origami ERC-721 implementation to customize `token_uri()`.

### Proposed Solution

* Create `ERC721MetadataHooksTrait `, containing a function `custom_uri()`, that can be implemented by the token contract.
* This function will be called internally by  called internally by `erc721_metadata_component::token_uri()` to customize its results.
* The custom hook implementation is optional, and if not implemented, the token contract will have to import `ERC721MetadataHooksEmptyImpl`, an empty implementation that should not affect the standard uri.

### Alternatives

Teh only way to customize the token uri is to clone `erc721_metadata_component` and use it on the token contract, instead of using Origami's own.

### Related Code

OpenZeppelin has similar hooks at their [ERC721](https://github.com/OpenZeppelin/cairo-contracts/blob/main/src/token/erc721/erc721.cairo) and [ERC20](https://github.com/OpenZeppelin/cairo-contracts/blob/main/src/token/erc20/erc20.cairo) implementations

### Additional context

This hook is required to allow fully on-chain metadata.

### If the feature is accepted, would you be willing to contribute it?

- [X] Yes I would be willing to contribute

**Comment by Ejembiii** [comment]
@rsodre I could work on this if it is yet to be assigned

**Comment by rsodre** [comment]
> @rsodre I could work on this since it is yet to be assigned

I'm not an admin on this repository.
But I'm already working on it for a personal project, and proposing a PR with my changes.

**Comment by rsodre** [comment]
note to the reviewer...

If that implementation is to your liking, I'm already working on a similar for the Balance component, adding `before_transfer()` and `after_transfer()` which depends on this one.
It includes some improvements to mintable and burnable (reusing `transfer_internal()` logic), and setting enumerable balances using the hooks, to reach the goal of removing all the transfer functions from the enumerable preset.
Once this is approved I can open the balance hooks.
